# .streamlit/secrets.toml
GEMINI_API_KEY = "AIzaSyCI3hg3O2N8I32bNmZZ2PjCp_7LzpQvyio" 
GOOGLE_SHEET_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSD7h4uAsxO_eqFm8BrcQBw0R93yHUU-CiO8cEkdXRefrip-ZdeSei9VRS6FepkM1_sZFCqtGc2eSt4/pub?gid=277001936&single=true&output=csv"
